CMOD_DEVMODE = true

-- Prices (set candle prices in candlegen.py and re-run)
DBLBOILERBUY = 150
DBLBOILERSELL = 60
CNDMAKERBUY = 150
CNDMAKERSELL = 60

-- Double Boiler values
DB_PROGRESS_MAX = 4
DB_PROGRESS_INCR = 0.05
DB_SMOKE_USED = 0.05
DB_SMOKE_MAX = 50
DB_SMOKE_INCR = 2
DB_WAX_CAPACITY = 3200
DB_WAX_PER_BEESWAX = 200
DB_HEATER_BOOST = 2

-- Candle Maker values
CM_PROGRESS_MAX = 4 -- Must be multiple of 4!
CM_DOWNARROW_MAX = 2
CM_PROGRESS_INCR = 0.4 --Must be divisible by 4!
CM_DOWNARROW_INCR = 0.1
CM_WAX_CAPACITY = 3200
CM_WAX_PER_CANDLE = 200
CM_COOLER_BOOST = 2